config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    #インデックス
    path('', views.IndexView.as_view(), name="index"),
    
    #問い合わせ
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),

    #日記一覧表示
    path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
    
    #日記詳細表示
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),

    #日記作成機能
    path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),

    #日記編集機能
    path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),

    #日記削除機能
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    #拡張ユーザーモデル

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.
class Diary(models.Model):
    #日記モデル

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'
    
    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Diary

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        #お名前
        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'        
        #メールアドレス
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'
        #タイトル
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'
        #メッセージ
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'
    
    def send_email(self):
        #ユーザー入力値を取得
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        #from_email = 'ksw2070042@stu.o-hara.ac.jp'
        to_list = [
            #複数人対応のため、配列形式になっている。
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        #EmailMessageインスタンスの生成
        finalMessage = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        #メッセージ送信
        finalMessage.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from diary.forms import InquiryForm
#from django.http.response import HttpResponse
from django.shortcuts import render
from django.views import generic
#メッセージ送信用
import logging
from django.urls import reverse_lazy
#メッセージ取得用
from django.contrib import messages

#日記一覧用
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary
#日記作成用（CRUDのC）
from diary.forms import DiaryCreateForm

#ロガーの取得
logger = logging.getLogger(__name__)

#インデックス（関数）
def index(request):
    #msg = request.GET['msg']
    #return HttpResponse('Your message : ' + msg)

    return render(request, 'diary/index.html')

#インデックス
class IndexView(generic.TemplateView):
    template_name = "diary/index.html"

#問い合わせ
class InquiryView(generic.FormView):
    template_name = "diary/inquiry.html"
    form_class = InquiryForm
    #「メッセージを送信しました。」画面のURL
    success_url = reverse_lazy('diary:inquiry')

    #メール送信
    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

#日記一覧表示
class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary/diary_list.html'
    paginate_by = 2

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at') #マイナス＝昇順
        return diaries

class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary/diary_detail.html'

class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary/diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False) #データに不足がある場合
        diary.user = self.request.user  #ログインしているユーザーのモデルオブジェクトをセット
        diary.save() #保存
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        #失敗したときに実行
        messages.error(self.request, '日記の作成に失敗しました。')
        return super().form_invalid(form)

class DiaryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = 'diary/diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})
    
    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, '日記の更新に失敗しました。')
        return super().form_invalid(form)

class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary/diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '日記を削除しました。')
        return super().delete(request, *args, **kwargs)

diary/templates/diary/base.html
<!-- staticディレクトリを参照 -->
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />

    <!-- タイトル挿入 -->
    <title>{% block title %}{% endblock %} | Private Diary</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- この例のカスタムフォント -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- この例のカスタムスタイル -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- 独自のスタイル -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrapper">
        <!-- ナビゲーション -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% block active_inquiry %}{% endblock %}"><a class="nav-link" href="{% url 'diary:inquiry' %}">INQUIRY</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item {% block active_diary_list %}{% endblock %}"><a class="nav-link" href="{% url 'diary:diary_list' %}">DIARY LIST</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <!-- ユーザーあり -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Log Out</a></li>
                        {% else %}
                        <!-- ログアウト状態 -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Log In</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- ヘッダーの挿入 -->
        {% block header %}{% endblock %}

        <!-- メッセージが存在する場合 -->
        {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        <!-- 全メッセージを表示する -->
                        {% for msg in messages %}
                        <li {% if msg.tags %} class="{{ msg.tags }}" {% endif %}>
                            {{ msg }}
                        </li>
                        {% endfor %}
                    </ul>
                    {{ msg }}
                </div>
            </div>
        </div>
        {% endif %}
        
        <!-- コンテンツの挿入 -->
        {% block contents %}{% endblock %}

        <!-- フッター -->
        <footer class="py-5 bg-black">
            <div class="container"><p class="m-0 text-center text-white small">Copyright &copy; Private Diary 2021</p></div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </div>
</body>
</html>

diary/templates/diary/diary_create.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}日記作成{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}

                <table class="table">
                    {{ form.as_table }}
                </table>

                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/diary_delete.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}日記削除{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a href="{% url 'diary:diary_detail' object.pk %}" class="btn btn-secondary mt-5 ml-2">
                    キャンセル
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/diary_detail.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}日記詳細{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <!-- タイトル -->
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>

        <hr>
        
        <!-- 本文 -->
        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>

        <hr>

        <!-- 写真3枚 -->
        <div class="row">
            <div class="col-3">
                <strong>写真</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                <img src="{{ object.photo1.url }}" width="200" height="200">
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                <img src="{{ object.photo2.url }}" width="200" height="200">
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                <img src="{{ object.photo3.url }}" width="200" height="200">
                {% endif %}
            </div>
        </div>

        <hr>

        <!-- 作成日時 -->
        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <!-- 更新日時 -->
        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>

        <!-- 編集ボタン -->
        <a href="{% url 'diary:diary_update' object.pk %}" class="btn btn-success mt-5 mb-3">
            編集
        </a>
        
        <!-- 削除ボタン -->
        <a href="{% url 'diary:diary_delete' object.pk %}" class="btn btn-danger mt-5 ml-2 mb-3">
            削除
        </a>
    </div>
</div>
{% endblock %}

diary/templates/diary/diary_list.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}日記一覧{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
                </div>

                {% for diary in diary_list %}
                <div class="post-preview">
                    <a href="{% url 'diary:diary_detail' diary.pk %}">
                        <h2 class="post-title">{{ diary.title }}</h2>
                        <h3 class="post-subtitle">{{ diary.content|truncatechars:20 }}</h3>
                    </a>
                    <p class="post-meta">{{ diary.created_at }}</p>
                </div>
                <hr>
                {% empty %}
                <p>日記がありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                <ul class="pagination">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                        <li class="page-item active">
                            <a href="#" class="page-link">{{ page_num }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/diary_update.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}日記編集{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <table class="table">
                    {{ form.as_table }}
                </table>

                <button class="btn btn-primary" type="submit">更新</button>
                <a href="{% url 'diary:diary_detail' object.pk %}" class="btn btn-secondary ml-2">
                    キャンセル
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/index.html
<!-- base.htmlを挿入 -->
{% extends 'diary/base.html' %}

<!-- staticディレクトリを参照 -->
{% load static %}

<!-- タイトル -->
{% block title %}Web上にあなた専用の日記ページを保存できるサービス{% endblock %}

<!-- ヘッダー -->
{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'account_login' %}">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

<!-- コンテンツ -->
{% block contents %}
<!-- コンテンツ セクション1（Web Diary） -->
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="" /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>Web上で作成/編集/削除ができる日記</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- コンテンツ セクション2（Save your Diary） -->
<section>
    <div class="container">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="" /></div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">Save your Diary</h2>
                    <p>あなたの日記をWebに保存</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- コンテンツ セクション3（Membership System） -->
<section>
    <div class="container">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="" /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>会員制のWeb日記サービス</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

diary/templates/diary/inquiry.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                <!-- CSRF対策 -->
                {% csrf_token %}

                <!-- エラーの取得 -->
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                        <!-- ラベル -->
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">
                        <!-- フィールド -->
                        {{ field }}
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}

                <!-- 送信ボタン -->
                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/template.html
{% extends 'diary/base.html' %}

{% load static %}

{% block title %}タイトル{% endblock %}

{% block header %}
<header class="masthead text-center text-white">
    ヘッダー
</header>
{% endblock %}

{% block contents %}
<!-- Content section 1-->
<section>
    <div class="container">
        コンテンツ
    </div>
</section>
{% endblock %}